# Generated by Django 3.0.7 on 2020-06-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('biryani', models.IntegerField(verbose_name='No. of biryani plates(Rs. 50 per plate)')),
                ('chicken', models.IntegerField(verbose_name='No. of packet of fried chciekn(Rs. 75 per packet. Each packet contains one quarter of a chicken)')),
            ],
        ),
    ]
