# Generated by Django 3.0.7 on 2020-06-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20200623_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cust_id',
            field=models.IntegerField(default=0, verbose_name='Mobile No.'),
            preserve_default=False,
        ),
    ]
